name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install typescript
      run: npm install typescript
    - name: tsc
      run: /home/runner/work/scrollspy/scrollspy/node_modules/typescript/bin/tsc -p ./src/tsconfig.json
